/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.Operaciones;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Estudiantes
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    String Texto;
    int a = 0, b = 0;
    int contar = 0, Resultado;
    char operacion, bases1 = 'd', bases2 = 'd';
    Operaciones op = new Operaciones();
    ArrayList<JButton> BHexa = new ArrayList<JButton>();
    ArrayList<JButton> BBina = new ArrayList<JButton>();
    ArrayList<JButton> BDeci = new ArrayList<JButton>();
    ArrayList<JButton> BOcta = new ArrayList<JButton>();

    public Calculadora() {
        initComponents();
        jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);

        BHexa.add(jButtonA);
        BHexa.add(jButtonB);
        BHexa.add(jButtonC);
        BHexa.add(jButtonD);
        BHexa.add(jButtonE);
        BHexa.add(jButtonF);
        BHexa.add(jButton0);
        BHexa.add(jButton1);
        BHexa.add(jButton2);
        BHexa.add(jButton3);
        BHexa.add(jButton4);
        BHexa.add(jButton5);
        BHexa.add(jButton6);
        BHexa.add(jButton7);
        BHexa.add(jButton8);
        BHexa.add(jButton9);

        BBina.add(jButton0);
        BBina.add(jButton1);

        BDeci.add(jButton0);
        BDeci.add(jButton1);
        BDeci.add(jButton2);
        BDeci.add(jButton3);
        BDeci.add(jButton4);
        BDeci.add(jButton5);
        BDeci.add(jButton6);
        BDeci.add(jButton7);
        BDeci.add(jButton8);
        BDeci.add(jButton9);

        BOcta.add(jButton0);
        BOcta.add(jButton1);
        BOcta.add(jButton2);
        BOcta.add(jButton3);
        BOcta.add(jButton4);
        BOcta.add(jButton5);
        BOcta.add(jButton6);
        BOcta.add(jButton7);

        jRadioDecimal.setSelected(true);
        buttonGroup1.add(jRadioDecimal);
        buttonGroup1.add(jRadioBinario);
        buttonGroup1.add(jRadioOctal);
        buttonGroup1.add(jRadioHexa);

        this.setTitle("Calculadora");
        this.setVisible(true);
        this.setResizable(false);
        this.setLocation(600, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonDividir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonResta = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBorrar = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jRadioDecimal = new javax.swing.JRadioButton();
        jRadioBinario = new javax.swing.JRadioButton();
        jRadioOctal = new javax.swing.JRadioButton();
        jRadioHexa = new javax.swing.JRadioButton();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jButtonDividir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDividir.setText("/");
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonMultiplicar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMultiplicar.setText("*");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonSuma.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSuma.setText("+");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonResta.setBackground(new java.awt.Color(204, 204, 204));
        jButtonResta.setText("-");
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton0.setBackground(new java.awt.Color(204, 204, 204));
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonBorrar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonBorrar.setText("A/C");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonIgual.setBackground(new java.awt.Color(204, 204, 204));
        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jRadioDecimal.setText("Decimal");
        jRadioDecimal.setFocusPainted(false);
        jRadioDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDecimalActionPerformed(evt);
            }
        });

        jRadioBinario.setText("Binario");
        jRadioBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBinarioActionPerformed(evt);
            }
        });

        jRadioOctal.setText("Octal");
        jRadioOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioOctalActionPerformed(evt);
            }
        });

        jRadioHexa.setText("Hexadecimal");
        jRadioHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioHexaActionPerformed(evt);
            }
        });

        jButtonA.setBackground(new java.awt.Color(204, 204, 204));
        jButtonA.setText("A");
        jButtonA.setEnabled(false);
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });

        jButtonB.setBackground(new java.awt.Color(204, 204, 204));
        jButtonB.setText("B");
        jButtonB.setEnabled(false);
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });

        jButtonC.setBackground(new java.awt.Color(204, 204, 204));
        jButtonC.setText("C");
        jButtonC.setEnabled(false);
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonD.setBackground(new java.awt.Color(204, 204, 204));
        jButtonD.setText("D");
        jButtonD.setEnabled(false);
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });

        jButtonE.setBackground(new java.awt.Color(204, 204, 204));
        jButtonE.setText("E");
        jButtonE.setEnabled(false);
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        jButtonF.setBackground(new java.awt.Color(204, 204, 204));
        jButtonF.setText("F");
        jButtonF.setEnabled(false);
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonBorrar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioBinario)
                            .addComponent(jRadioHexa)
                            .addComponent(jRadioDecimal)
                            .addComponent(jRadioOctal))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioDecimal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioBinario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioOctal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
        // TODO add your handling code here:
        if (jLabel1.getText() == "") {
            JOptionPane.showMessageDialog(rootPane, "Deberias introducir algún numero");
        } else {
            if (contar == 0) {
                operacion = 'd';
                contar++;
                if (a == 0) {
                    a = Integer.parseInt(jLabel1.getText());
                }
                jLabel1.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Deberia presionar \" = \" ");

            }
        }
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed
        // TODO add your handling code here:
        if (jLabel1.getText() == "") {
            JOptionPane.showMessageDialog(rootPane, "Deberias introducir algún numero");
        } else {
            if (contar == 0) {
                operacion = 'm';
                contar++;
                if (a == 0) {
                    a = Integer.parseInt(jLabel1.getText());
                }
                jLabel1.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Deberia presionar \" = \" ");

            }
        }
    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        // TODO add your handling code here:
        if (jLabel1.getText() == "") {
            JOptionPane.showMessageDialog(rootPane, "Deberias introducir algún numero");
        } else {
            if (contar == 0) {
                operacion = 's';
                contar++;
                if (a == 0) {
                    a = Integer.parseInt(jLabel1.getText());
                }
                jLabel1.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Deberia presionar \" = \" ");
            }
        }
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed
        // TODO add your handling code here:
        if (jLabel1.getText() == "") {
            JOptionPane.showMessageDialog(rootPane, "Deberias introducir algún numero");
        } else {
            if (contar == 0) {
                operacion = 'r';
                contar++;
                if (a == 0) {
                    a = Integer.parseInt(jLabel1.getText());
                }
                jLabel1.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Deberia presionar \" = \" ");
            }
        }
    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Texto = jLabel1.getText();

        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "1");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("");
        contar = 0;

    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "2");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "3");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "4");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "5");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "6");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "7");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "8");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "9");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "0");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here:
        if (jLabel1.getText() == "") {
            JOptionPane.showMessageDialog(rootPane, "Deberias introducir algún numero");
        }
        switch (bases1) {
            case 'd':
                b = Integer.parseInt(jLabel1.getText());
                break;
            case 'b':
                b = Integer.parseInt(jLabel1.getText(), 2);
                jLabel1.setText(Integer.toString(a));
                break;
            case 'o':
                b = Integer.parseInt((jLabel1.getText()), 8);
                jLabel1.setText(Integer.toString(a));
                break;
            case 'h':
                b = Integer.parseInt((jLabel1.getText()), 16);
                jLabel1.setText(Integer.toString(a));
                break;
        }

        switch (operacion) {
            case 's':
                Resultado = op.suma(a, b);
                break;
            case 'r':
                Resultado = op.resta(a, b);
                break;
            case 'm':
                Resultado = op.multiplicacion(a, b);
                break;
            case 'd':
                if (b == 0) {
                    JOptionPane.showMessageDialog(rootPane, "El divisor no puede ser cero");
                } else {
                    Resultado = op.division(a, b);
                }
                break;

            default:
                JOptionPane.showMessageDialog(rootPane, "Deberias elegir una operación");
                break;
        }

        switch (bases1) {
            case 'd':
                jLabel1.setText(Integer.toString(Resultado));
                break;
            case 'b':
                jLabel1.setText(Integer.toBinaryString(Resultado));
                break;
            case 'o':
                jLabel1.setText(Integer.toOctalString(Resultado));
                break;
            case 'h':
                jLabel1.setText(Integer.toHexString(Resultado));
                break;
        }


    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jRadioDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDecimalActionPerformed
        // TODO add your handling code here:

        for (Iterator<JButton> iterator = BHexa.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(false);
        }
        for (Iterator<JButton> iterator = BDeci.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(true);
        }
        if (jLabel1.getText() != "") {
            switch (bases1) {
                case 'd':
                    break;
                case 'b':
                    a = Integer.parseInt(jLabel1.getText(), 2);
                    jLabel1.setText(Integer.toString(a));
                    break;
                case 'o':
                    a = Integer.parseInt((jLabel1.getText()), 8);
                    jLabel1.setText(Integer.toString(a));
                    break;
                case 'h':
                    a = Integer.parseInt((jLabel1.getText()), 16);
                    jLabel1.setText(Integer.toString(a));
                    break;
            }
        }
        bases1 = 'd';
    }//GEN-LAST:event_jRadioDecimalActionPerformed

    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "a");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "b");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "c");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "d");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonDActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "e");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        String Texto = jLabel1.getText();
        if (Texto.length() < 13) {
            jLabel1.setText(Texto + "f");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hay demasiados numeros");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonFActionPerformed

    private void jRadioBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBinarioActionPerformed
        // TODO add your handling code here:
        for (Iterator<JButton> iterator = BDeci.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(false);
        }
        for (Iterator<JButton> iterator = BHexa.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(false);
        }
        for (Iterator<JButton> iterator = BBina.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(true);
        }
        if (jLabel1.getText() != "") {
            switch (bases1) {
                case 'd':
                    a = Integer.parseInt(jLabel1.getText());
                    jLabel1.setText(Integer.toBinaryString(a));
                    break;
                case 'b':
                    break;
                case 'o':
                    a = Integer.parseInt(jLabel1.getText(), 8);
                    jLabel1.setText(Integer.toBinaryString(a));
                    break;
                case 'h':
                    a = Integer.parseInt(jLabel1.getText(), 16);
                    jLabel1.setText(Integer.toBinaryString(a));
                    break;
            }
        }
        bases1 = 'b';
    }//GEN-LAST:event_jRadioBinarioActionPerformed

    private void jRadioHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioHexaActionPerformed
        // TODO add your handling code here:
        for (Iterator<JButton> iterator = BDeci.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(true);
        }
        for (Iterator<JButton> iterator = BHexa.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(true);
        }
        if (jLabel1.getText() != "") {
            switch (bases1) {
                case 'd':
                    a = Integer.parseInt(jLabel1.getText());
                    jLabel1.setText(Integer.toHexString(a));
                    break;
                case 'b':
                    a = Integer.parseInt(jLabel1.getText(), 2);
                    jLabel1.setText(Integer.toHexString(a));
                    break;
                case 'o':
                    a = Integer.parseInt((jLabel1.getText()), 8);
                    jLabel1.setText(Integer.toHexString(a));
                    break;
                case 'h':
                    break;
            }
        }
        bases1 = 'h';
    }//GEN-LAST:event_jRadioHexaActionPerformed

    private void jRadioOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioOctalActionPerformed
        // TODO add your handling code here:
        for (Iterator<JButton> iterator = BHexa.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(false);
        }
        for (Iterator<JButton> iterator = BDeci.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(false);
        }
        for (Iterator<JButton> iterator = BOcta.iterator(); iterator.hasNext();) {
            JButton next = iterator.next();
            next.setEnabled(true);
        }
        if (jLabel1.getText() != "") {
            switch (bases1) {
                case 'd':
                    a = Integer.parseInt(jLabel1.getText());
                    jLabel1.setText(Integer.toOctalString(a));
                    break;
                case 'b':
                    a = Integer.parseInt(jLabel1.getText(), 2);
                    jLabel1.setText(Integer.toOctalString(a));
                    break;
                case 'o':
                    break;
                case 'h':
                    a = Integer.parseInt(jLabel1.getText(), 16);
                    jLabel1.setText(Integer.toOctalString(a));
                    break;
            }
        }
        bases1 = 'o';

    }//GEN-LAST:event_jRadioOctalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioBinario;
    private javax.swing.JRadioButton jRadioDecimal;
    private javax.swing.JRadioButton jRadioHexa;
    private javax.swing.JRadioButton jRadioOctal;
    // End of variables declaration//GEN-END:variables
}
